
# -*- coding: utf-8 -*-
"""contract_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2-VW6T0lDAfFKpPqdUFGQbI56c2pv9e
"""

# 1. Install and Import Libraries
import pandas as pd
import numpy as np
import time
from nba_api.stats.endpoints import leaguedashplayerstats
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error

# --- FORMATTING SETTING (Prevents Scientific Notation) ---
pd.options.display.float_format = '{:,.2f}'.format

# 2. Configuration & Constants
CAP_2026_PROJECTED = 155100000
CAPS = {2023: 136021000, 2024: 140588000, 2025: 155100000}
SEASON_MAP = {2023: '2022-23', 2024: '2023-24', 2025: '2024-25'}

# 3. Data Cleaning & Logic Helpers
def clean_currency(val):
    if pd.isna(val) or val == '': return 0
    return float(str(val).replace('$', '').replace(',', '').strip())

def get_max_cap_pct(yoe):
    """Max contract tiers based on Years of Experience"""
    if yoe >= 10: return 0.35
    if yoe >= 7:  return 0.30
    return 0.25

def parse_fa_type(type_str):
    """Classifies the Type column from your 2026 sheet."""
    t = str(type_str).upper()
    status, rights, opt_val = "UFA", "Non-Bird", 0

    if "RFA" in t: status = "RFA"
    elif "PLAYER" in t: status = "Player Option"
    elif "CLUB" in t: status = "Club Option"

    if "BIRD" in t and "EARLY" not in t: rights = "Full Bird"
    elif "EARLY BIRD" in t: rights = "Early Bird"

    if "$" in t:
        try: opt_val = float(t.split('$')[1].replace('M', '')) * 1_000_000
        except: pass
    return status, rights, opt_val

# 4. Training Data Collection
all_training_data = []
for year, season in SEASON_MAP.items():
    print(f"Processing training data for {year}...")
    trad = leaguedashplayerstats.LeagueDashPlayerStats(season=season, per_mode_detailed='Totals').get_data_frames()[0]
    adv = leaguedashplayerstats.LeagueDashPlayerStats(season=season, measure_type_detailed_defense='Advanced').get_data_frames()[0]
    stats = pd.merge(trad, adv[['PLAYER_ID', 'TS_PCT', 'USG_PCT', 'PIE']], on='PLAYER_ID')

    # Select filename based on year
    if year == 2023: fname = '2023 NBA Free Agents.csv'
    elif year == 2024: fname = '2024 NBA Free Agents.csv'
    else: fname = '2025 NBA Free Agents (1).csv'

    fa_df = pd.read_csv(fname)
    p_col = [c for c in fa_df.columns if 'Player' in c][0]
    a_col = [c for c in fa_df.columns if 'AAV' in c][0]
    fa_df = fa_df[[p_col, a_col]].rename(columns={p_col: 'Player', a_col: 'Actual_AAV'})
    fa_df['Actual_AAV'] = fa_df['Actual_AAV'].apply(clean_currency)

    merged = pd.merge(stats, fa_df, left_on='PLAYER_NAME', right_on='Player')
    merged['Cap_Pct'] = merged['Actual_AAV'] / CAPS[year]
    all_training_data.append(merged)
    time.sleep(1)

df_train = pd.concat(all_training_data).dropna()

# 5. Fit Lasso Regression
features = ['AGE', 'GP', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT',
            'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
            'PF', 'NBA_FANTASY_PTS', 'DD2', 'TD3', 'PLUS_MINUS', 'TS_PCT', 'USG_PCT', 'PIE']

X, y = df_train[features], df_train['Cap_Pct']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
lasso = LassoCV(cv=5, random_state=42).fit(X_scaled, y)

# 6. Predict 2026 Free Agents
print("Fetching 2025-26 live stats...")
live_trad = leaguedashplayerstats.LeagueDashPlayerStats(season='2024-25', per_mode_detailed='Totals').get_data_frames()[0]
live_adv = leaguedashplayerstats.LeagueDashPlayerStats(season='2024-25', measure_type_detailed_defense='Advanced').get_data_frames()[0]
live_df = pd.merge(live_trad, live_adv[['PLAYER_ID', 'TS_PCT', 'USG_PCT', 'PIE']], on='PLAYER_ID')

# Load and Parse 2026 FA List
fa_2026 = pd.read_csv('NBA Free Agents 2026 - Sheet1.csv', skiprows=1)
fa_2026[['Status', 'Rights', 'Option_Value']] = fa_2026['Type'].apply(lambda x: pd.Series(parse_fa_type(x)))

# THE FIX: Merge and immediately rename the player column to 'Player'
final_2026 = pd.merge(live_df, fa_2026, left_on='PLAYER_NAME', right_on='Player (248)')
final_2026 = final_2026.rename(columns={'PLAYER_NAME': 'Player'})

# Run Predictions
X_2026 = scaler.transform(final_2026[features])
final_2026['Predicted_Cap_Pct'] = lasso.predict(X_2026)

# Apply CBA Constraints
final_2026['Max_Allowed_Pct'] = final_2026['YOE'].apply(get_max_cap_pct)
final_2026['Final_Cap_Pct'] = np.minimum(final_2026['Predicted_Cap_Pct'], final_2026['Max_Allowed_Pct'])
final_2026['Est_AAV'] = final_2026['Final_Cap_Pct'] * CAP_2026_PROJECTED
final_2026['Prev_AAV_Num'] = final_2026['Prev AAV'].apply(clean_currency)

# 7. Add Market Notes
def generate_notes(row):
    notes = []
    if row['Status'] == 'RFA': notes.append("RFA")
    if row['Rights'] == 'Full Bird': notes.append("5-Yr Max Eligible")
    if row['Status'].endswith('Option'): notes.append(f"Opt: ${row['Option_Value']:,.0f}")
    if row['Predicted_Cap_Pct'] > row['Max_Allowed_Pct']: notes.append("Max Value")
    return " | ".join(notes) if notes else "Standard UFA"

final_2026['Market_Analysis'] = final_2026.apply(generate_notes, axis=1)

# 8. Output Table
print("\n--- 2026 LIVE FREE AGENT ESTIMATOR ---")
# 'Player' is now properly in the index because of the rename above
cols = ['Player', 'Age', 'Status', 'Rights', 'Prev_AAV_Num', 'Est_AAV', 'Market_Analysis']
output_table = final_2026[cols].sort_values('Est_AAV', ascending=False).head(25)
print(output_table.to_string(index=False))

# 1. Install and Import
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import seaborn as sns
from nba_api.stats.endpoints import leaguedashplayerstats
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler

# --- FORMATTING & STYLE ---
pd.options.display.float_format = '{:,.2f}'.format
sns.set_theme(style="whitegrid")

# 2. Configuration
CAP_2026_PROJECTED = 155100000
CAPS = {2023: 136021000, 2024: 140588000, 2025: 155100000}
SEASON_MAP = {2023: '2022-23', 2024: '2023-24', 2025: '2024-25'}

# 3. Helpers
def clean_currency(val):
    if pd.isna(val) or val == '': return 0
    return float(str(val).replace('$', '').replace(',', '').strip())

def get_max_cap_pct(yoe):
    if yoe >= 10: return 0.35
    if yoe >= 7:  return 0.30
    return 0.25

def parse_fa_type(type_str):
    t = str(type_str).upper()
    status, rights, opt_val = "UFA", "Non-Bird", 0
    if "RFA" in t: status = "RFA"
    elif "PLAYER" in t: status = "Player Option"
    elif "CLUB" in t: status = "Club Option"
    if "BIRD" in t and "EARLY" not in t: rights = "Full Bird"
    elif "EARLY BIRD" in t: rights = "Early Bird"
    if "$" in t:
        try: opt_val = float(t.split('$')[1].replace('M', '')) * 1_000_000
        except: pass
    return status, rights, opt_val

# 4. Train Model on Historical Data
all_training_data = []
for year, season in SEASON_MAP.items():
    print(f"Training on {season} data...")
    trad = leaguedashplayerstats.LeagueDashPlayerStats(season=season, per_mode_detailed='Totals').get_data_frames()[0]
    adv = leaguedashplayerstats.LeagueDashPlayerStats(season=season, measure_type_detailed_defense='Advanced').get_data_frames()[0]
    stats = pd.merge(trad, adv[['PLAYER_ID', 'TS_PCT', 'USG_PCT', 'PIE']], on='PLAYER_ID')

    fname = '2023 NBA Free Agents.csv' if year == 2023 else ('2024 NBA Free Agents.csv' if year == 2024 else '2025 NBA Free Agents (1).csv')
    fa_df = pd.read_csv(fname)
    p_col = [c for c in fa_df.columns if 'Player' in c][0]
    a_col = [c for c in fa_df.columns if 'AAV' in c][0]
    fa_df = fa_df[[p_col, a_col]].rename(columns={p_col: 'Player', a_col: 'Actual_AAV'})
    fa_df['Actual_AAV'] = fa_df['Actual_AAV'].apply(clean_currency)

    merged = pd.merge(stats, fa_df, left_on='PLAYER_NAME', right_on='Player')
    merged['Cap_Pct'] = merged['Actual_AAV'] / CAPS[year]
    all_training_data.append(merged)
    time.sleep(1)

df_train = pd.concat(all_training_data).dropna()
features = ['AGE', 'GP', 'MIN', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'PLUS_MINUS', 'TS_PCT', 'USG_PCT', 'PIE']
X, y = df_train[features], df_train['Cap_Pct']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
lasso = LassoCV(cv=5, random_state=42).fit(X_scaled, y)

# 5. Live 2025-26 Predictions
print("Pulling LIVE 2025-26 stats...")
# We pull current season stats to see who is increasing their value right now
live_trad = leaguedashplayerstats.LeagueDashPlayerStats(season='2025-26', per_mode_detailed='Totals').get_data_frames()[0]
live_adv = leaguedashplayerstats.LeagueDashPlayerStats(season='2025-26', measure_type_detailed_defense='Advanced').get_data_frames()[0]
live_df = pd.merge(live_trad, live_adv[['PLAYER_ID', 'TS_PCT', 'USG_PCT', 'PIE']], on='PLAYER_ID')

fa_2026 = pd.read_csv('NBA Free Agents 2026 - Sheet1.csv', skiprows=1)
fa_2026[['Status', 'Rights', 'Option_Value']] = fa_2026['Type'].apply(lambda x: pd.Series(parse_fa_type(x)))

final_2026 = pd.merge(live_df, fa_2026, left_on='PLAYER_NAME', right_on='Player (248)')
final_2026 = final_2026.rename(columns={'PLAYER_NAME': 'Player'})

# Run Predictor
X_2026 = scaler.transform(final_2026[features])
final_2026['Predicted_Cap_Pct'] = lasso.predict(X_2026)
final_2026['Max_Allowed_Pct'] = final_2026['YOE'].apply(get_max_cap_pct)
final_2026['Final_Cap_Pct'] = np.minimum(final_2026['Predicted_Cap_Pct'], final_2026['Max_Allowed_Pct'])

final_2026['Est_AAV'] = final_2026['Final_Cap_Pct'] * CAP_2026_PROJECTED
final_2026['Prev_AAV_Num'] = final_2026['Prev AAV'].apply(clean_currency)

# CALCULATE THE "VALUE DELTA" (Market Gain/Loss)
final_2026['Value_Delta'] = final_2026['Est_AAV'] - final_2026['Prev_AAV_Num']

# 6. LIVE VISUALIZATION: Top 15 Contract Gainers
plt.figure(figsize=(12, 8))
top_gainers = final_2026.sort_values('Value_Delta', ascending=False).head(15)

barplot = sns.barplot(
    data=top_gainers,
    x='Value_Delta',
    y='Player',
    hue='Status',
    palette='viridis'
)

plt.title('2026 Free Agency: Top Contract Value Gainers\n(Predicted 2026 AAV vs. Previous Contract)', fontsize=16)
plt.xlabel('Increase in Annual Salary ($)', fontsize=12)
plt.ylabel('Player', fontsize=12)

# Add dollar labels to the bars
for i, p in enumerate(barplot.patches):
    val = top_gainers.iloc[i]['Value_Delta']
    barplot.annotate(f'${val/1e6:.1f}M',
                   (val, i),
                   ha='left', va='center',
                   xytext=(5, 0),
                   textcoords='offset points')

plt.tight_layout()
plt.show()

# 7. Final Table
print("\n--- 2026 MARKET VALUE TABLE ---")
cols = ['Player', 'Prev_AAV_Num', 'Est_AAV', 'Value_Delta', 'Status', 'PIE']
print(final_2026[cols].sort_values('Value_Delta', ascending=False).head(20).to_string(index=False))

# 1. Setup and Imports
import pandas as pd
import numpy as np
import time
from datetime import datetime
from nba_api.stats.endpoints import leaguedashplayerstats
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler

# --- CONFIGURATION ---
pd.options.display.float_format = '{:,.2f}'.format
TRACKER_FILE = 'nba_contract_tracker.csv'
CAP_2026_PROJECTED = 155100000
CAPS = {2023: 136021000, 2024: 140588000, 2025: 155100000}
SEASON_MAP = {2023: '2022-23', 2024: '2023-24', 2025: '2024-25'}

FEATURES = ['AGE', 'GP', 'MIN', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'PLUS_MINUS', 'TS_PCT', 'USG_PCT', 'PIE']

# 2. Logic Helpers
def clean_currency(val):
    if pd.isna(val) or val == '': return 0
    return float(str(val).replace('$', '').replace(',', '').strip())

def get_max_cap_pct(yoe):
    if yoe >= 10: return 0.35
    if yoe >= 7:  return 0.30
    return 0.25

def parse_fa_type(type_str):
    t = str(type_str).upper()
    status, rights, opt_val = "UFA", "Non-Bird", 0
    if "RFA" in t: status = "RFA"
    elif "PLAYER" in t: status = "Player Option"
    elif "CLUB" in t: status = "Club Option"
    if "BIRD" in t and "EARLY" not in t: rights = "Full Bird"
    elif "EARLY BIRD" in t: rights = "Early Bird"
    if "$" in t:
        try: opt_val = float(t.split('$')[1].replace('M', '')) * 1_000_000
        except: pass
    return status, rights, opt_val

# 3. Model Training (Run this once per session)
def train_contract_model():
    print("Training Lasso Model on historical data...")
    all_data = []
    for year, season in SEASON_MAP.items():
        trad = leaguedashplayerstats.LeagueDashPlayerStats(season=season, per_mode_detailed='Totals').get_data_frames()[0]
        adv = leaguedashplayerstats.LeagueDashPlayerStats(season=season, measure_type_detailed_defense='Advanced').get_data_frames()[0]
        stats = pd.merge(trad, adv[['PLAYER_ID', 'TS_PCT', 'USG_PCT', 'PIE']], on='PLAYER_ID')

        fname = f'2023 NBA Free Agents.csv' if year == 2023 else (f'2024 NBA Free Agents.csv' if year == 2024 else '2025 NBA Free Agents (1).csv')
        fa_df = pd.read_csv(fname)
        p_col = [c for c in fa_df.columns if 'Player' in c][0]
        a_col = [c for c in fa_df.columns if 'AAV' in c][0]
        fa_df = fa_df[[p_col, a_col]].rename(columns={p_col: 'Player', a_col: 'Actual_AAV'})
        fa_df['Actual_AAV'] = fa_df['Actual_AAV'].apply(clean_currency)

        merged = pd.merge(stats, fa_df, left_on='PLAYER_NAME', right_on='Player')
        merged['Cap_Pct'] = merged['Actual_AAV'] / CAPS[year]
        all_data.append(merged)
        time.sleep(1)

    df_train = pd.concat(all_data).dropna()
    X, y = df_train[FEATURES], df_train['Cap_Pct']
    scaler = StandardScaler().fit(X)
    X_scaled = scaler.transform(X)
    model = LassoCV(cv=5, random_state=42).fit(X_scaled, y)
    return model, scaler

# 4. The Weekly Update Function (The "Living" Data Frame Generator)
def run_weekly_update(model, scaler):
    print(f"Running update for {datetime.today().strftime('%Y-%m-%d')}...")

    # A. Fetch Live 2025-26 Stats
    live_trad = leaguedashplayerstats.LeagueDashPlayerStats(season='2025-26', per_mode_detailed='Totals').get_data_frames()[0]
    live_adv = leaguedashplayerstats.LeagueDashPlayerStats(season='2025-26', measure_type_detailed_defense='Advanced').get_data_frames()[0]
    live_df = pd.merge(live_trad, live_adv[['PLAYER_ID', 'TS_PCT', 'USG_PCT', 'PIE']], on='PLAYER_ID')

    # B. Load and Match 2026 Free Agent List
    fa_2026 = pd.read_csv('NBA Free Agents 2026 - Sheet1.csv', skiprows=1)
    fa_2026[['Status', 'Rights', 'Option_Value']] = fa_2026['Type'].apply(lambda x: pd.Series(parse_fa_type(x)))

    # C. Prediction Pipeline
    final = pd.merge(live_df, fa_2026, left_on='PLAYER_NAME', right_on='Player (248)')
    X_live = scaler.transform(final[FEATURES])

    final['Snapshot_Date'] = datetime.today().strftime('%Y-%m-%d')
    final['Predicted_Cap_Pct'] = model.predict(X_live)

    # Apply CBA Caps
    final['Max_Allowed_Pct'] = final['YOE'].apply(get_max_cap_pct)
    final['Final_Cap_Pct'] = np.minimum(final['Predicted_Cap_Pct'], final['Max_Allowed_Pct'])
    final['Predicted_AAV'] = final['Final_Cap_Pct'] * CAP_2026_PROJECTED

    # D. Structure for Output
    # We keep only essential columns for the App's visualization
    output_cols = ['PLAYER_NAME', 'Snapshot_Date', 'Predicted_AAV', 'PIE', 'PTS', 'Status', 'Rights']
    new_snapshot = final[output_cols].rename(columns={'PLAYER_NAME': 'Player'})

    # E. Append to Living CSV
    try:
        existing_df = pd.read_csv(TRACKER_FILE)
        updated_df = pd.concat([existing_df, new_snapshot], ignore_index=True)
        # Prevent duplicate entries for the same day
        updated_df = updated_df.drop_duplicates(subset=['Player', 'Snapshot_Date'], keep='last')
    except FileNotFoundError:
        updated_df = new_snapshot

    updated_df.to_csv(TRACKER_FILE, index=False)
    print(f"Successfully updated {TRACKER_FILE}. Total records: {len(updated_df)}")
    return new_snapshot

# --- EXECUTION ---
# Step 1: Train the model (Do this once)
model, scaler = train_contract_model()

# Step 2: Run the update (This is what you run 'weekly')
weekly_data = run_weekly_update(model, scaler)

# Preview the current snapshot
print("\n--- Current Snapshot (Top 10) ---")
print(weekly_data.sort_values('Predicted_AAV', ascending=False).head(10))
